### ISSUE TITLE
"bash INSTALL.sh correlation " error

### ISSUE THREAD

**Issue by jingfenglanyun** [DeepMotionAIResearch/DenseMatchingBenchmark#14]
**env : ubuntu18.04 + torch1.5 + cuda10.2**
**error message:**
......
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/seiriosai/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/seiriosai/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'build_ext': BuildExtension
  File "/home/seiriosai/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
........
....
File "/home/seiriosai/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
cp: 无法获取'build/lib*' 的文件状态(stat): 没有那个文件或目录

**Comment by jingfenglanyun** [comment]
This error is solved by modify "dmb.ops.correlation.setup.py"
**from** 

```
setup(
    name='correlation_cuda',
    ext_modules=[
        CUDAExtension('correlation_cuda', [
            'correlation_cuda.cc',
            'correlation_cuda_kernel.cu'
        ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
```

**to**
```
setup(
    name='correlation_cuda',
    ext_modules=[
        CUDAExtension('correlation_cuda', [
            'correlation_cuda.cc',
            'correlation_cuda_kernel.cu'
        ])
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
```

**Comment by youmi-zym** [comment]
Problem solved. Thanks.
