### ISSUE TITLE
An error is reported after use dict(type='TensorboardLoggerHook') in log_config

### ISSUE THREAD

**Issue by LewisYI** [DeepMotionAIResearch/DenseMatchingBenchmark#22]
**My environment:
Pytorch1.7.1+tensorboardX2.1+mmcv1.3.5

If I uncomment "dict(type='TensorboardLoggerHook')" in "configs/AcfNet/scene_flow_adaptive.py", I can avoid this problem but can't get the log of the Tensorboard...**

Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 114, in main
    train_matcher(
  File "/home/liuyi/graduation_thesis/DenseMatchingBenchmark-master/dmb/apis/train.py", line 76, in train_matcher
    _dist_train(model, train_dataset, cfg, eval_dataset, vis_dataset, validate=validate, logger=logger)
  File "/home/liuyi/graduation_thesis/DenseMatchingBenchmark-master/dmb/apis/train.py", line 181, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/hooks/logger/base.py", line 158, in after_train_epoch
    self.log(runner)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/liuyi/graduation_thesis/DenseMatchingBenchmark-master/dmb/utils/tensorboard_logger.py", line 94, in log
    self.single_log(tag, record, global_step)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/liuyi/graduation_thesis/DenseMatchingBenchmark-master/dmb/utils/tensorboard_logger.py", line 66, in single_log
    if record.size > 1:
TypeError: '>' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/liuyi/anaconda3/envs/dense_matching_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/liuyi/anaconda3/envs/dense_matching_benchmark/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/AcfNet/scene_flow_adaptive.py', '--launcher', 'pytorch', '--validate', '--gpus', '4']' returned non-zero exit status 1.

**Comment by youmi-zym** [comment]
Hi @LewisYI,
It seems the problem happens here: 

if record.size > 1:
TypeError: '>' not supported between instances of 'builtin_function_or_method' and 'int'

you can try to print the record to see the type at [here](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/dmb/utils/tensorboard_logger.py#L66). Basically, we just want to check the object, i.e., record, is an image or scalar.

**Comment by LewisYI** [comment]
> Hi @LewisYI, It seems the problem happens here:
> 
> if record.size > 1: TypeError: '>' not supported between instances of 'builtin_function_or_method' and 'int'
> 
> you can try to print the record to see the type at [here](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/dmb/utils/tensorboard_logger.py#L66). Basically, we just want to check the object, i.e., record, is an image or scalar.

Hi, @youmi-zym, 
thank you for your advice, I check record here: 
        print('This is record:\n')
        print(record)
        print('\n End record:\n')
        if record.size > 1:
            self.writer.add_image(tag, record, global_step)
        else:
            self.writer.add_scalar(tag, record, global_step)

This is the output with no errors:
This is record:
5.039224243164062
End record:
This is record:
3.9991355299949647
End record:
This is record:
16.357464838027955
 End record:

And this is the output when the error reported:
2021-12-30 20:38:39,857 - INFO - Start Visualizing on SceneFlow dataset(5 images).
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 8/5, 2.8 task/s, elapsed: 3s, ETA:     0s

2021-12-30 20:38:44,209 - INFO - Epoch [1] Visualization Finished!
2021-12-30 20:38:44,257 - INFO - Saving checkpoint at 1 epochs
2021-12-30 20:38:44,423 - INFO - Epoch [1][274/274]     lr: 0.00139, 
This is record:

tensor([43.2085])

 End record:

I find this happen at the last one of each epoch, Maybe this is a problem with the mmcv version?
The bug happens when the record turns to be a tensor instead of a scalar like 16.357464838027955.

**Comment by youmi-zym** [comment]
Hi @LewisYI,
I think you can use float(record) or other similar operations to avoid this bug.
